typography_spectrum: 0.9477394276764244
color:
  brandStrength: 0.7595037291757762
  lightness: 0.8828693442046642
  saturation: 0.14367115311324596
  rhythmicContrast: 0.45972201018594205
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.11520293517969549
author:
  name: Jeffrey Krueger
  email: ecowilliam@gmail.com
name: Deep in Japan Podcast
navigation:
  - name: Amazon Affiliate Link
    url: www.amazon.com
    type: external
title: Deep in Japan
description: 'Rich, insightful interviews with people who live in Japan.'
